### ISSUE TITLE
Create method(s) to process output files into time series

### ISSUE THREAD

**Issue by dadamsncsa** [c3aidti/training-space-ids#300]
## Description

Create method to process files and create the timeseries. I think this would best be done as a dynamic batch job, see: the 'Dynamic Batch Job' section here: https://developer.c3.ai/docs/7.24.0/guide/guide-c3aisuite-basic/c3-plat-dynamic-distributed-job-tutorial. I think the job should take a reprocess=False argument. We might even be able to add a call to this in another afterCreate callback to automate the processing.

This can start as a member function for the SimulationOutputFile type.  Then the dynamic batch job can process all of the output file with `processed == false`

**Comment by babreu-ncsa** [comment]
#361 took care of this
