### ISSUE TITLE
Visualize data and move towards emulation

### ISSUE THREAD

**Issue by hgordo** [c3aidti/training-space-ids#382]
## Steps To Complete
- [x] Get python environment right in jupyter notebook
- [x] Make some plots 
- [ ] look into Gaussian processes

## References
* [Contributing](https://github.com/c3aidti/training-space-ids/blob/920cac4820ee5921217500969b15407b4e19755d/.github/CONTRIBUTING.md)

**Comment by babreu-ncsa** [comment]
I know that you will not be able to do this right away, cause when I tried to install the kernel I got an error indicating that Anaconda was not able to find the cartopy package that was specified, but the above comment will be helpful once this is solved (I'm taking a look at it)

**Comment by hgordo** [comment]
hi Bruno, that's great, thank you for this nice detective work! I was able to make a plot in the jupyter notebook using cartopy now.
