### ISSUE TITLE
Possible issue with afterCreate on Gordon Project

### ISSUE THREAD

**Issue by dadamsncsa** [c3aidti/training-space-ids#457]
Hey @babreu-ncsa.  I was trying to sync all the dev nodes again and ran into an error.  Not that this only happens the first time a provision is attempted on a tag.  If  I re-run, it clears up.  But it might be good to track it down eventually.

Here's the dump from the provisioner
<html>
{fileUrl:"meta://training/dti-jupyter/package.json",lineNum:0,colNum:0,severity:"ERROR",message:"[Message] Invalid or inaccessible URL azure://aircraft-observations/mrg1_P3 for azure\n\n  from action AzureFileSystem.listFiles\n  from env_server.js, line 132\n    130    if (C3._context.locale)\n    131      options.language = C3._context.locale;\n  > 132    return c3CallAction(target, args, options);\n    133  }\n    134  \n  from typesys.js, line 1684\n    1682  \n    1683          // call the server to execute this function as an action\n  > 1684          response = c3Call(this, name, args);\n    1685        }\n    1686  \n  from ObservationSet_afterCreate.js, line 28\n    26      var pathToFiles = 'azure://' + obj.prePathToFiles + '/' ...\n    27  \n  > 28      var observationFiles = FileSystem.inst().listFiles(pathT...\n    29      // Remove non-NetCDF files from list and filter correct ...\n    30      for (var i = 0; i < observationFiles.length; i++) {\n  from third-party/underscore.js, line 123\n    121      for (var index = 0; index < length; index++) {\n    122        currentKey = keys ? keys[index] : index;\n  > 123        results[index] = iteratee(obj[currentKey], currentKey, obj);\n    124      }\n    125      return results;\n  from compat_obj.js, line 28\n    26     */\n    27    C3.typesys.Enumerable.prototype.map = function (iterator, ...\n  > 28      var result = _.map(this, iterator, context);\n    29      if (!valueType) {\n    30        var firstVal, i;\n  from ObservationSet_afterCreate.js, line 16\n    14  \n    15  function afterCreate(objs) {\n  > 16    var files = objs.map(createFiles);\n    17    files.forEach(upsertBatch);\n    18    return;\n  from ObservationSet_afterCreate.js, line 93\n    91  })();\n    92  if (typeof $ObservationSet$functions.afterCreate == 'function') {\n  > 93    function afterCreate() { return $ObservationSet$functions....\n    94  }\n    95  \n  from ObservationSet_afterCreate.js, line 1360\n    1358  if (typeof afterCreate != 'function') throw new Error('Funct...\n    1359  global$.call$ObservationSet$afterCreate = function(objs) {\n  > 1360    return afterCreate.call(this, objs);\n    1361  };\n    1362  })(this);\n  base action ObservationSet.afterCreate"}
{fileUrl:"meta://training/dti-jupyter/package.json",lineNum:0,colNum:0,severity:"ERROR",message:"[Message] Invalid or inaccessible URL azure://aircraft-observations/mrg1_P3 for azure\n\n  from action AzureFileSystem.listFiles\n  from env_server.js, line 132\n    130    if (C3._context.locale)\n    131      options.language = C3._context.locale;\n  > 132    return c3CallAction(target, args, options);\n    133  }\n    134  \n  from typesys.js, line 1684\n    1682  \n    1683          // call the server to execute this function as an action\n  > 1684          response = c3Call(this, name, args);\n    1685        }\n    1686  \n  from ObservationSet_afterCreate.js, line 28\n    26      var pathToFiles = 'azure://' + obj.prePathToFiles + '/' ...\n    27  \n  > 28      var observationFiles = FileSystem.inst().listFiles(pathT...\n    29      // Remove non-NetCDF files from list and filter correct ...\n    30      for (var i = 0; i < observationFiles.length; i++) {\n  from third-party/underscore.js, line 123\n    121      for (var index = 0; index < length; index++) {\n    122        currentKey = keys ? keys[index] : index;\n  > 123        results[index] = iteratee(obj[currentKey], currentKey, obj);\n    124      }\n    125      return results;\n  from compat_obj.js, line 28\n    26     */\n    27    C3.typesys.Enumerable.prototype.map = function (iterator, ...\n  > 28      var result = _.map(this, iterator, context);\n    29      if (!valueType) {\n    30        var firstVal, i;\n  from ObservationSet_afterCreate.js, line 16\n    14  \n    15  function afterCreate(objs) {\n  > 16    var files = objs.map(createFiles);\n    17    files.forEach(upsertBatch);\n    18    return;\n  from ObservationSet_afterCreate.js, line 93\n    91  })();\n    92  if (typeof $ObservationSet$functions.afterCreate == 'function') {\n  > 93    function afterCreate() { return $ObservationSet$functions....\n    94  }\n    95  \n  from ObservationSet_afterCreate.js, line 1360\n    1358  if (typeof afterCreate != 'function') throw new Error('Funct...\n    1359  global$.call$ObservationSet$afterCreate = function(objs) {\n  > 1360    return afterCreate.call(this, objs);\n    1361  };\n    1362  })(this);\n  base action ObservationSet.afterCreate"}
</html>

**Comment by babreu-ncsa** [comment]
The Azure blob is only configured for tc02d, I think... If you provision the packaged to other tags, it will fail

**Comment by babreu-ncsa** [comment]
Makes sense that it is only the first time, because that method is called by afterCreate()... so the second time you try, the table is already there and the method is not called

**Comment by babreu-ncsa** [comment]
which makes me think that, since we are using the dev tags independently, syncing them is not necessary and can cause errors

**Comment by dadamsncsa** [comment]
I see.  Interesting issue.
We can stop syncing dev tags, but then we no longer have a single integrated application.  I guess we should decide if that is what we want.  
If, on the other hand, we want to (in theory) be able to deploy on multiple tags ,it is probably advisable to only use the cluster-configured Azure blob, or configure any new mounts cluster wide.

**Comment by babreu-ncsa** [comment]
During our Development meeting, we decided to continue using the same workflows. For now, we should always try to avoid configurations at the **tag** level to avoid this sort of issue.

Additionally, when working with **cron jobs**, care must be taken.

**Comment by babreu-ncsa** [comment]
- [] Configure blob at cluster level
