### ISSUE TITLE
Implement anisotropic Matern and predicted std for GPs

### ISSUE THREAD

**Issue by JamesCarzon** [c3aidti/training-space-ids#548]
## Description

The scikit-learn Matern kernel for Gaussian process regression allows for specifying an anisotropic kernel. We would like to be able to do this for the C3 ML GP pipeline. Additionally, we would like to be able to obtain predicted standard deviations and covariances from the pipeline as well as the predictions themselves.

## Steps To Complete
- [x] Allow for the Matern length scale to be specified as an array of length equal to the number of inputs in the regressor
- [x] Allow for the Matern kernel lead coefficient parameter to be learned (e.g. the constant _c_ in `k(x,y) = c^2 * Matern(|x-y|)`)
- [x] Ensure that the C3 kernel type is storing the learned parameter values after fitting the regressor, not just retaining the initial values
- [x] Have a method for obtaining the fitted parameter (i.e. an analogy to the method `sklearn.gaussian_process.kernel_.get_params()`)
- [x] Have a method for returning the predicted standard deviations from the fitted GP (i.e. an analogy to the method `sklearn.gaussian process.GaussianProcessRegressor(kernel).predict(return std, return cov)`)

## References
* [Contributing](https://github.com/c3aidti/training-space-ids/blob/920cac4820ee5921217500969b15407b4e19755d/.github/CONTRIBUTING.md)
* [scikit-learn Matern kernel documentation](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.Matern.html#sklearn.gaussian_process.kernels.Matern.theta)

**Comment by JamesCarzon** [comment]
@babreu-ncsa I would like to try to provision the recent commits I've made which are toward the above issues, but I do not know to which branch I should make my pull request (if any).

**Comment by babreu-ncsa** [comment]
@JamesCarzon which branch are you currently on? (`git status` will tell you). You should make the changes from the branch `gordon-dev` and then, after committing and pushing, open a pull request **from** `gordon-dev` to `tc02d`, which will trigger the provisioning workflow

**Comment by JamesCarzon** [comment]
#549 fails. I would like lengthScales to be an array, but writing `lengthScales: Float32Array` is not the way to do it.

**Comment by JamesCarzon** [comment]
I don't believe we are currently returning the predicted covariances with the GaussianProcessRegressionPipe's process method, the last task of the issue, but this can be done easily later. This comment is to keep the issue open.

**Comment by babreu-ncsa** [comment]
The last checkbox was covered in the end of PR #557
